### ISSUE TITLE
String literals are printed without double quotes

### ISSUE THREAD

**Issue by raymoo** [osa1/language-lua#34]
```pprint $ L.String "bob"``` results in ```"bob"``` rather than ```"\"bob\""```

**Comment by osa1** [comment]
This is not a bug: We include quotes in the parsed `String`. The reason is because we want to be able to print parsed files exactly the way they were written originally. So, if I have a string `[===[bob]===]`, I should get exactly the same string when I parse and then print.

Try this in your repl:

```
λ> parseText exp "\"bob\""
Right (String "\"bob\"")
λ> fmap pprint (parseText exp "[[bob]]")
Right [[bob]]
λ> fmap pprint (parseText exp "[==[bob]==]")
Right [==[bob]==]
λ> fmap pprint (parseText exp "'bob'")
Right 'bob'
λ> fmap pprint (parseText exp "\"bob\"")
Right "bob"
```

If you want to generate `String`s manually, just use whatever a valid Lua string quoting syntax in the string.

**Comment by raymoo** [comment]
Alright, thank you.
